### ISSUE TITLE
Where are the videos saved and which format is used?

### ISSUE THREAD

**Issue by bolein** [Isvisoft/flutter_screen_recording#1]

**Comment by salime45** [comment]
Hi

In android the videos saved in the DIRECTORY_DCIM.

In iOS the videos saved in the documentDirectory

The format is mp4. 

We are working in the lib right now .

**Comment by bolein** [comment]
You mean it's still in active development? I would like to use it for my project as well, so I might end up making a fork of it.

**Comment by bolein** [comment]
@salime45 I'm not getting any logs from the iOS code into the console. Any suggestions?

**Comment by salime45** [comment]
We create this plugin for a own project, we release because not exists nothing like this for flutter if you want improve the plugin be welcome.

If you need any help you can email me.

Thanks

**Comment by bolein** [comment]
I have an idea of creating a native to flutter video recorder that takes advantage of the Flutter rendering engine. Would you be interested to participate in the development?

**Comment by salime45** [comment]
Of course, can be very interesting. I tried some things with the screenshot plugin, https://github.com/SachinGanesh/screenshot but i dont know enough of flutter

**Comment by tanmaydarmorha-vidooly** [comment]
how can we change the directory where videos are saved?

**Comment by salime45** [comment]
unfortunately the path is not configurable.
