### ISSUE TITLE
flutter_screen_recording` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by shankark6666** [Isvisoft/flutter_screen_recording#101]
The plugin `flutter_screen_recording` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Launching lib\main.dart on SM G990E in debug mode...

C:\flutter demo\video_demo\android>if "Windows_NT" == "Windows_NT" setlocal

C:\flutter demo\video_demo\android>set DEFAULT_JVM_OPTS=

C:\flutter demo\video_demo\android>set DIRNAME=C:\flutter demo\video_demo\android\

C:\flutter demo\video_demo\android>if "C:\flutter demo\video_demo\android\" == "" set DIRNAME=.

C:\flutter demo\video_demo\android>set APP_BASE_NAME=gradlew

C:\flutter demo\video_demo\android>set APP_HOME=C:\flutter demo\video_demo\android\

C:\flutter demo\video_demo\android>if defined JAVA_HOME goto findJavaFromJavaHome

C:\flutter demo\video_demo\android>set JAVA_HOME=C:\Program Files\Android\Android Studio\jbr

C:\flutter demo\video_demo\android>set JAVA_EXE=C:\Program Files\Android\Android Studio\jbr/bin/java.exe

C:\flutter demo\video_demo\android>if exist "C:\Program Files\Android\Android Studio\jbr/bin/java.exe" goto init

C:\flutter demo\video_demo\android>if not "Windows_NT" == "Windows_NT" goto win9xME_args

C:\flutter demo\video_demo\android>if "@eval[2+2]" == "4" goto 4NT_args

C:\flutter demo\video_demo\android>set CMD_LINE_ARGS=

C:\flutter demo\video_demo\android>set _SKIP=2

C:\flutter demo\video_demo\android>if "x-q" == "x" goto execute

C:\flutter demo\video_demo\android>set CMD_LINE_ARGS=-q -Ptarget-platform=android-arm64 "-Ptarget=C:\flutter demo\video_demo\lib\main.dart" -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9jZjdhOWQwODAwZjJhNWRhMTY2ZGJlMGViOWZiMjQ3NjAxODI2OWIxLw== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug

C:\flutter demo\video_demo\android>goto execute

C:\flutter demo\video_demo\android>set CLASSPATH=C:\flutter demo\video_demo\android\\gradle\wrapper\gradle-wrapper.jar

C:\flutter demo\video_demo\android>"C:\Program Files\Android\Android Studio\jbr/bin/java.exe"    "-Dorg.gradle.appname=gradlew" -classpath "C:\flutter demo\video_demo\android\\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain -q -Ptarget-platform=android-arm64 "-Ptarget=C:\flutter demo\video_demo\lib\main.dart" -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9jZjdhOWQwODAwZjJhNWRhMTY2ZGJlMGViOWZiMjQ3NjAxODI2OWIxLw== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
Parameter format not correct -

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations$ReflectSdkVersion found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.jvm.jdk8.JvmRepeatableKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.jvm.optionals.OptionalsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

C:\flutter demo\video_demo\android>if "1" == "0" goto mainEnd

C:\flutter demo\video_demo\android>rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of

C:\flutter demo\video_demo\android>rem the _cmd.exe /c_ return code!

C:\flutter demo\video_demo\android>if not "" == "" exit 1

C:\flutter demo\video_demo\android>exit /b 1
Exception: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by azazadev** [comment]
Any updates on this? Is the package still maintained? If not, can anyone recommend an alternative for screen recording compatible with Flutter?

**Comment by acastry** [comment]
Hi,
is this package maintained ? updated ?
Regards,

**Comment by fettespferd** [comment]
I would also be interested in knowing if it will ever get updated.

**Comment by TNorbury** [comment]
PR is open. See the PR description for instructions on how to use my branch in your project
