### ISSUE TITLE
 notificationTitle parameter has been removed which is causing the app to break on new version

### ISSUE THREAD

**Issue by David-codes0** [Isvisoft/flutter_screen_recording#111]
../../../../.pub-cache/hosted/pub.dev/flutter_screen_recording-2.0.11/lib/flutter_screen_recording.dart:20:7: Error: No named parameter with the name 'notificationTitle'.
      notificationTitle: titleNotification, 
      ^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flutter_screen_recording-2.0.11/lib/flutter_screen_recording.dart:31:7: Error: No named parameter with the name 'notificationTitle'.
      notificationTitle: titleNotification ?? "",
      ^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by tgthiag2** [comment]
same issue

**Comment by xiuxiu123888** [comment]
same issue

**Comment by salime45** [comment]
fix
