### ISSUE TITLE
MethodChannelFlutterScreenRecording.startRecordScreen has fewer named arguments

### ISSUE THREAD

**Issue by sumanrajpathak** [Isvisoft/flutter_screen_recording#113]
../../../.pub-cache/hosted/pub.dev/flutter_screen_recording_platform_interface-1.0.2/lib/method_channel_flutter_screen_recording.dart:12:16: Error: The method 'MethodChannelFlutterScreenRecording.startRecordScreen' has fewer named arguments than those of overridden method 'FlutterScreenRecordingPlatform.startRecordScreen'.
  Future<bool> startRecordScreen(String name) async {
               ^
../../../.pub-cache/hosted/pub.dev/flutter_screen_recording_platform_interface-1.0.2/lib/flutter_screen_recording_platform_interface.dart:30:16: Context: This is the overridden method ('startRecordScreen').
  Future<bool> startRecordScreen(String name, {
               ^
../../../.pub-cache/hosted/pub.dev/flutter_screen_recording_platform_interface-1.0.2/lib/method_channel_flutter_screen_recording.dart:18:16: Error: The method 'MethodChannelFlutterScreenRecording.startRecordScreenAndAudio' has fewer named arguments than those of overridden method 'FlutterScreenRecordingPlatform.startRecordScreenAndAudio'.
  Future<bool> startRecordScreenAndAudio(String name) async {
               ^
../../../.pub-cache/hosted/pub.dev/flutter_screen_recording_platform_interface-1.0.2/lib/flutter_screen_recording_platform_interface.dart:37:16: Context: This is the overridden method ('startRecordScreenAndAudio').
  Future<bool> startRecordScreenAndAudio(String name,{

**Comment by salime45** [comment]
fix

**Comment by sumanrajpathak** [comment]
> fix

Thank you @salime45
