### ISSUE TITLE
Error prepare failed

### ISSUE THREAD

**Issue by GHCode1997** [Isvisoft/flutter_screen_recording#16]
My console:
I/MediaRecorderJNI(22574): setup
I/System.out(22574): Original Resolution
I/System.out(22574): 720 x 1450
I/System.out(22574): Calcule Resolution
I/System.out(22574): 635 x 1280
I/MediaRecorderJNI(22574): setVideoSource(2)
W/MediaRecorder(22574): setOutputFile: path = /storage/emulated/0/DCIM/Title.mp4
E/Media_APM : (22574): isCalledPackage return false
I/MediaRecorderJNI(22574): setVideoSize(635, 1280)
I/MediaRecorderJNI(22574): setVideoEncoder(2)
I/MediaRecorderJNI(22574): setParameter()
I/MediaRecorderJNI(22574): setVideoFrameRate(60)
W/MediaRecorder(22574): prepare: mPath = /storage/emulated/0/DCIM/Title.mp4
I/MediaRecorderJNI(22574): setOutputFile
I/MediaRecorderJNI(22574): prepare
E/MediaRecorder(22574): prepare failed: -2147483648
D/--INIT-RECORDER(22574): prepare failed.

PS C:\Users\Gustavo Huerta\Documents\proyects\screenrecord> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [VersiÃ³n 10.0.18363.836], locale es-CL)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)
• No issues found!

**Comment by GHCode1997** [comment]
Using example in documentation

**Comment by salime45** [comment]
That is the last version? In the last version should appear the scale density

What device are you using?

In my experience when you try to record the screen with a low reoslution like 635 the MediaRecorder doesnt work.

Can you try to modify maxRes in calculeResolution with a higher value?

**Comment by GHCode1997** [comment]
Yes, using the last version.

I have a samsung j6 2018.

I do not know how to do it modify maxRes in calculeResolution

**Comment by salime45** [comment]
And whta is the scale density of your device?

The function to edit is in 
flutter_screen_recording/android/src/main/kotlin/com/isvisoft/flutter_screen_recording/FlutterScreenRecordingPlugin.kt

**Comment by salime45** [comment]
No answer. I close the issue . 
If anyone have the same problem please inform us.
Thanks
