### ISSUE TITLE
Voice is not getting recorded on my Samsung A70 device !

### ISSUE THREAD

**Issue by hasanrihawi** [Isvisoft/flutter_screen_recording#19]
although i gave audio permission to app, still no luck in recording device voice, only able to record video

**Comment by hasanrihawi** [comment]
you need to add those lines:

```
            mMediaRecorder?.setAudioSource(MediaRecorder.AudioSource.MIC);
            mMediaRecorder?.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
            mMediaRecorder?.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
```
into file FlutterScreenRecordingPlugin.kt in order to start recording voice

**Comment by salime45** [comment]
Yes, we have to add a flag and logic for that in the futrure, rigth now the plugin only record screen
