### ISSUE TITLE
NoSuchMethodError on starting recording

### ISSUE THREAD

**Issue by svadhis** [Isvisoft/flutter_screen_recording#2]
When I use startRecordScreen, app crashes and I get an error : 

_`java.lang.NoSuchMethodError: No virtual method onActivityResult(ILandroid/content/Intent;Landroid/app/Activity;)V in class Lcom/hbisoft/hbrecorder/HBRecorder; or its super classes (declaration of 'com.hbisoft.hbrecorder.HBRecorder' appears in /data/app/com.....`_

I'm using the exact same code as in the example given

**Comment by salime45** [comment]
I think you dont install correctly HbRecorder. https://github.com/HBiSoft/HBRecorder

**Comment by rrarey02** [comment]
I am having the same issue, but I followed the instructions to modify my root- and app-level build.gradle files with the repository and dependency information. Any ideas?

**Comment by salime45** [comment]
what android version you use?

If not found the library you need check the Hbrecorder installation
