### ISSUE TITLE
Access to individual frames?

### ISSUE THREAD

**Issue by Nolence** [Isvisoft/flutter_screen_recording#20]
Hi!

Is there a way to add access to individual frames of the video in order to process them in some way? I also wouldn't necessarily need to save the video in any place so long as it was a stream of individual frames of the screen.

Thank you

**Comment by salime45** [comment]
I think the Android/ios libraries not permit that. Although you can to try to post process the video after this is save with some library and get the frames you need

**Comment by Nolence** [comment]
Thanks for the information!

Was just curious

**Comment by sayhicoelho** [comment]
> I think the Android/ios libraries not permit that. Although you can to try to post process the video after this is save with some library and get the frames you need

What about live streaming apps?
