### ISSUE TITLE
Support for audio recording.

### ISSUE THREAD

**Issue by prashantspandey** [Isvisoft/flutter_screen_recording#21]
Hello guys .
This plugin is recording video successfully . But it is not able to record audio. Can you please add this feature?
Thanks

**Comment by salime45** [comment]
We are working in this right now.

**Comment by dannycortesv** [comment]
bool started = FlutterScreenRecording.startRecordScreenAndAudio(videoName);

Does this work to record screen video with audio on both iOS and Android?

**Comment by vvalladolidIV** [comment]
Currently It only works on Android. We are still working on iOS.

**Comment by rgb1380** [comment]
Any estimates when audio will be ready for iOS?

**Comment by salime45** [comment]
We don't know. We will inform with news when the plugin ready

**Comment by mikron123** [comment]
would also love to have the functionality on iOS. Thanks!

**Comment by vvalladolidIV** [comment]
There is available a new version on develop branch with the funcionality. Could you try it?

**Comment by mikron123** [comment]
How do I include a certain branch in the yaml?

**Comment by mikron123** [comment]
> There is available a new version on develop branch with the functionality. Could you try it?

- Recording once works, then if you try to record 2 times in a row, it crashes. After re-opening the app, the recording failed even on the 1st attempt...
- Volume of recording is very low

- Recording in landscape mode records the screen vertically stretched.

**Comment by vvalladolidIV** [comment]
¿What is your device? We are trying with Iphone Xr (iOS 13.5.1) and iPad 5ºGeneración (iOS 13.3)

- Can not reproduce that error.
- The volume is fine.
- We have knowledge about it error but... We can still not reproduce it

**Comment by mikron123** [comment]
iPhone 6 iOS 12.4.7 & iPad Pro 9.7 iOS 13.5.1

- The crash happened only with the last version and tested so far only on the iPhone 6 iOS 12.4.7
- Same device with low volume from mic


- Landscape bug: Before recording I perform

    SystemChrome.setPreferredOrientations([
          DeviceOrientation.landscapeRight,
          DeviceOrientation.landscapeLeft,
      ]);
    SystemChrome.setEnabledSystemUIOverlays([]);

And I hold the device horizontally.

**Comment by mikron123** [comment]
Also use     Wakelock.enable();

**Comment by MohammadEhsanMirzaaee** [comment]
work fine on my phone"iphone xs max"
how can I use dev branch in flutter project?
