### ISSUE TITLE
Example app crashes on iOS

### ISSUE THREAD

**Issue by rgb1380** [Isvisoft/flutter_screen_recording#24]
Example app crashes on iOS.

Steps to reproduce:
- Edit pubspecs.yaml of the example comment the local reference to the plug-in library and point to the online repo as per below:
flutter_screen_recording: ^1.0.8
\#  flutter_screen_recording:
\#    path: ../
- Build the example app for iOS.
- Start recording 
- The app crashes with no logs or error.

The issue was observed on physical device (iPhone 7 plus running iOS 13.5.1) and on a simulator.

**Comment by salime45** [comment]
Can you try to use the github repository directly?

**Comment by rgb1380** [comment]
It worked before when the github repo was used locally. The problem is with the online repo.

I also tried it in our own app and linked directly and no crash happening there and recording works.
What could be the problem with the online repo on pub.dev?

**Comment by salime45** [comment]
i mean this way 

  flutter_screen_recording:
    git:
      url: https://github.com/isvisoft/flutter_screen_recording.git

I think there are some commits not publish in pub.dev

**Comment by rgb1380** [comment]
It works when using the github repo directly, as well.
Will be good to keep this issue open until the issue with the pub.dev package is solved. Thanks.

**Comment by salime45** [comment]
i update in pub.dev try the 1.0.10 version

**Comment by rgb1380** [comment]
Great! Has been fixed in 1.0.10.
