### ISSUE TITLE
Use Platform Interface so easier to add Web and other platforms?

### ISSUE THREAD

**Issue by JohnGalt1717** [Isvisoft/flutter_screen_recording#25]
It would be really nice of this used the new platform interface design so that we could add support for web etc. I'm happy to write the web integration since most browsers now support this once it's in platform interface design pattern.

**Comment by salime45** [comment]
Hi @JohnGalt1717 i don't know the new platform interface design but we will delighted if you add web support

**Comment by JohnGalt1717** [comment]
Here's what I' referring to: https://medium.com/flutter/modern-flutter-plugin-development-4c3ee015cf5a

https://medium.com/flutter/flutter-platform-channels-ce7f540a104e

This will allow Web (and others eventually) to be added easily once this is refactored to use this methodology for plugins.

**Comment by salime45** [comment]
You can make a pull request if you want.Thanks

**Comment by JohnGalt1717** [comment]
That's a big refactor. I'd feel more comfortable if that was done by a maintainer because I'm not experienced in iOS so I wouldn't be able to complete the migration over.

**Comment by salime45** [comment]
What do you think if you fork and prepare the android part and then we program ios?

**Comment by JohnGalt1717** [comment]
My Android is ok, but I don't even have a machine setup to do it on.  The web is straight forward because I've already done it in the past. The platform stuff is basically being required going forward especially for desktop platforms so it's basically a pre-req.

**Comment by JohnGalt1717** [comment]
Why was this closed? Any future plugin development in Flutter basically requires this to be done especially for future platforms. They've outright said that the old way will be depreciated in the next year.

**Comment by JohnGalt1717** [comment]
I've implemented the platform interface logic using the current channel interface as the default for now so that the code should just work.  This code is required to move forward with Web which I plan to implement next once this is published.

Thanks.

Per the ones, someone else will need to update the ios and android implementations to implement the interface per https://medium.com/flutter/how-to-write-a-flutter-web-plugin-part-2-afdddb69ece6 and the recommended best practices for federated plugins, although it can wait for now.  Note that the new system is significantly more performant once implemented.
