### ISSUE TITLE
How to record screen for particular widget in flutter?

### ISSUE THREAD

**Issue by suriyaKalidoss123** [Isvisoft/flutter_screen_recording#26]
Currently, In your plugin, the screen record is done for fullscreen, How to record only a particular area in the screen or particular widget.Please guide

**Comment by suriyaKalidoss123** [comment]
Refer this for more Info:https://stackoverflow.com/questions/62813972/how-to-screen-record-particular-widget-in-flutter

**Comment by salime45** [comment]
I think the Android/ios libraries not permit that. Although you can to try to post process the video after this is save with some library and get the area you need
