### ISSUE TITLE
Implement Web

### ISSUE THREAD

**Issue by JohnGalt1717** [Isvisoft/flutter_screen_recording#31]
I have web code implemented. It depends on the Platform Interface code pull request I did before.

The pull request is here: https://github.com/Isvisoft/flutter_screen_recording/pull/30

There are no tests at this time.

**Comment by salime45** [comment]
For the moment the code is in the web branch, we will gonna do test in the other platforms and merge in master.  Thanks

**Comment by JohnGalt1717** [comment]
Sounds good.

**Comment by JohnGalt1717** [comment]
Any movement on getting this all integrated?

**Comment by jhancock4d** [comment]
*bump*
