### ISSUE TITLE
[Crash] App crashes on Android 10

### ISSUE THREAD

**Issue by mikron123** [Isvisoft/flutter_screen_recording#33]
Need to be a MediaProjection service for Android 10. 

Plugin needs to be upgraded to support Android 10.

Thanks

**Comment by salime45** [comment]
I try in different devices and emulator with this version and works fine. 

Can you tell me a emulator where this not works?

**Comment by mikron123** [comment]
wasn't on emulator. only on real devices.. happened on a XiaoMi 8 and Google Pixel.
The reason was not initiating a 'ForegroundService'

**Comment by salime45** [comment]
you mean it is not crashing in an emulator? We dont have this devices, Can you make the changes in the code?

**Comment by mikron123** [comment]
Another reason the I found is that the calculated resolution wasn't right for the Mi 8.. 
windowManager.defaultDisplay.getRealSize(screenSize); should be used to get the screen size, and then use the ratio with
val screenRatio : Double = (screenSize.x.toDouble()  / screenSize.y.toDouble())

then we can use the ratio to calculate a give width.
mDisplayWidth = 1280;
mDisplayHeight = mDisplayWidth / screenRatio;

**Comment by salime45** [comment]
160/5000
That code doesn't work on all devices. We disapprove of it for that.
Each Android device treats the resolution at which it can record differently

**Comment by mikron123** [comment]
I've tested it on all emulator + devices that crashed before and it works.. the problem is you relied on the resolution minus the status bar... which caused the crash.

I've committed some changed, you're welcome to test them.

**Comment by mikron123** [comment]
There's an Android Camera API to get all available recording resolutions, but Camera is deprecated, Camera 2 is not.
The realSize + Ratio calculation worked on all tested devices and prevented the crash in some.. so I don't see the problem.

**Comment by salime45** [comment]
Merge in develop branch

**Comment by FiveFingerDeathPunch** [comment]
when mDisplayWidth and mDisplayHeight can be divisible by 10.it s work

**Comment by kenle** [comment]
I believe there is a new security feature in Android 10 that is a breaking change for screen recording unfortunately.  Must run a foreground service type "mediaProjection".

Related issue:
https://stackoverflow.com/questions/61276730/media-projections-require-a-foreground-service-of-type-serviceinfo-foreground-se

Check these plugins for examples of what may need to be implemented:
https://pub.dev/packages/foreground_service
https://pub.dev/packages/flutter_foreground_plugin

Possible important additions into the Manifest when using foreground service:
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>`
`<service android:name="---service package name---" android:foregroundServiceType="mediaProjection" />`

**Comment by salime45** [comment]
I removed the code from the example and put inside the plugin. Should work now in any android device.

Is in branch develop
