### ISSUE TITLE
can not work in the example

### ISSUE THREAD

**Issue by caipeng-hrv** [Isvisoft/flutter_screen_recording#34]
when I press the button which named record screen,it happen below. 
 PS: my flutter is 1.17.1, my phone's android version is 10

I/System.out(28700): Scaled Density
I/System.out(28700): 3.0
I/System.out(28700): Original Resolution
I/System.out(28700): 1080 x 2208
I/System.out(28700): Calcule Resolution
I/System.out(28700): 939 x 1920
W/cording_example(28700): type=1400 audit(0.0:3036725): avc: granted { read write } for pid=28700 name="Title.mp4" dev="sdcardfs" ino=280996 scontext=u:r:untrusted_app_27:s0:c143,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
E/MediaRecorder(28700): prepare failed: -2147483648
D/--INIT-RECORDER(28700): prepare failed.
I/System.out(28700): Error startRecordScreen
I/System.out(28700): prepare failed.
D/HwFrameworkSecurityPartsFactory(28700): HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory(28700): add HwFrameworkSecurityPartsFactory to memory.
D/ZrHung.AppEyeUiProbe(28700): not watching, wait.
D/ZrHung.AppEyeUiProbe(28700): restart watching

**Comment by salime45** [comment]
Seems https://github.com/Isvisoft/flutter_screen_recording/issues/33

**Comment by salime45** [comment]
Check develop branch
