### ISSUE TITLE
record screen even app is in the background?

### ISSUE THREAD

**Issue by MohammadEhsanMirzaaee** [Isvisoft/flutter_screen_recording#37]
Hi,
is there any way to record screen even app is in the background?
record other apps, like default ios screen recorder

**Comment by salime45** [comment]
In the example you can minimize the app and continue recording. When you want stop you can go to the app again and stopped

**Comment by MohammadEhsanMirzaaee** [comment]
in iOS the app pause recording when the app goes in the background and then back to the app it continues recording
