### ISSUE TITLE
record in background iOS

### ISSUE THREAD

**Issue by MohammadEhsanMirzaaee** [Isvisoft/flutter_screen_recording#40]
In iOS the app pause recording when the app goes in the background and then back to the app it continues recording

**Comment by salime45** [comment]
I think this is not posible in iOS. If you find anything we can study

**Comment by MohammadEhsanMirzaaee** [comment]
it's possible by iOS broadcast
https://bambuser.com/docs/broadcasting/ios-swift/
but the difference from this link, you should stream it to AVKit or one of the similar tools
