### ISSUE TITLE
Record with audio is not working

### ISSUE THREAD

**Issue by tanmoy27112000** [Isvisoft/flutter_screen_recording#42]
This is the error that is printed in the terminal when using a record screen with audio.

D/permissions_handler( 9128): No android specific permissions needed for: 9
I/flutter ( 9128): Foreground on Started
E/MediaRecorder( 9128): setAudioSource called in an invalid state(4)
I/System.out( 9128): Error onMethodCall startRecordScreen
I/System.out( 9128): null
I/flutter ( 9128): current datetime is 2020-10-05 09:37:31.223983

**Comment by abdullah432** [comment]
Any solution?

**Comment by zxl777** [comment]
Yes, I also encountered the same problem. How to solve the problem that "Record Screen & audio" does not work?

**Comment by admarwick** [comment]
While working on [PR #49] (https://github.com/Isvisoft/flutter_screen_recording/pull/49) I noticed that the audio recording was working. So once that PR lands it might solve your problem.

**Comment by MalazTamim** [comment]
same issue, any solution?

**Comment by sha3rawi33** [comment]
same issue!

**Comment by salime45** [comment]
Fix
