### ISSUE TITLE
ios simulator

### ISSUE THREAD

**Issue by biancashouse** [Isvisoft/flutter_screen_recording#43]
Should it work on simulator ?
I trued several devices and it loses connection on startup.

**Comment by salime45** [comment]
i never try this in a ios simulator. Cant you use a real device?

**Comment by programmermasrawy** [comment]
it doesn't work in real device too

**Comment by biancashouse** [comment]
i only have an old ipad 2. Trying not to buy more apple crap. I'll use my
pixel 3a instead.

**Comment by salime45** [comment]
What ios version have the ipad 2?

**Comment by biancashouse** [comment]
iOS 9 - you would not even be able to install latest gmail app on that ;-)
I notice that Apple have a the ReplyKit api for screen recording.
Perhaps I should learn enough swift so I can create a pkg to integrate with
that...
Which api(s) are you using ?

**Comment by biancashouse** [comment]
BTW - I would like to be able to record MacOS screen, but Apple web page
says you need xcode 12+.
That's crazy.
