### ISSUE TITLE
How to suppress warning "Exposing sensitive info during casting/recording"

### ISSUE THREAD

**Issue by admarwick** [Isvisoft/flutter_screen_recording#46]
Thanks for this useful plugin. I'm running it on the Android Emulator built for Pixel 3a and Android api 29, i.e. Android 10. It works fine except that a warning dialog always appears. The title is "Exposing sensitive info during casting/recording". Is there a way to suppress that programmatically?

Edit: The same thing happens on a Samsung Galaxy S9 running Android 10. I was not able to find a place to turn off this warning in Settings. I'd like to be able to control it from an app.

**Comment by salime45** [comment]
That dialog is from operating system, we dont have control about that
