### ISSUE TITLE
Screen Size Issues

### ISSUE THREAD

**Issue by admarwick** [Isvisoft/flutter_screen_recording#47]
Two problems show up when using the plugin on a physical Galaxy S9 running Android 10, i.e. not an emulator. Both problems have to do with the way the plugin configures the screen size to MediaRecorder.

To Duplicate

1. Run the example project with the phone in portait orientation and press the "Record Screen" button. The log shows a call to MediaRecorder.setVideoSize(1280, 720). Press the "Stop" button. 
2. Recording is successful. Use the back button to return to the example app screen.
3. Press "Record Screen" button again. The log shows a call to MediaRecorder.setVideoSize(1280, 2631) -- a different size. This is **Problem number 1**.
4. The log also shows error messages: prepare failed: -2147483648. Recording does not take place. This is **Problem number 2**.

Configuration

 Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-US)

**Comment by admarwick** [comment]
Please note that [PR #49](https://github.com/Isvisoft/flutter_screen_recording/pull/49) addresses this issue.

**Comment by salime45** [comment]
Fix
