### ISSUE TITLE
Flutter Screen Record not recording full screen but only top header of the app

### ISSUE THREAD

**Issue by MilotH2** [Isvisoft/flutter_screen_recording#48]
Hello everyone, 

The issue right now is so that when I start to record, and stop it, it works, it creates the screen record and the video, but it does NOT record the full screen of it.

[Click here for a streamable video link from stramable.com](https://streamable.com/s1je2k)

Since in the plugin, right now, it does not say that i can set video screen size, its a bit strange because it records only top of the app and not the whole full screen.

What i also realized, it recorded only a fraction of it and not whole 15 seconds that i did.

Let me know what I am missing, Thank you.

this is the code:

`  startScreenRecord(bool audio) async {
    print('test');
    bool start = false;
    await Future.delayed(const Duration(milliseconds: 1000));

    if (audio) {
      print('test2');
      start = await FlutterScreenRecording.startRecordScreenAndAudio(
          "Title" + _time.toString(),
          titleNotification: "dsffad",
          messageNotification: "sdffd");
    } else {
      print('test3');
      start = await FlutterScreenRecording.startRecordScreen("Title2",
          titleNotification: "dsffad", messageNotification: "sdffd");
    }

    if (start) {
      print('start');
      setState(() => recording = !recording);
    }

    return start;
`
  }
  stopScreenRecord() async {
    print('stop');
    String path = await FlutterScreenRecording.stopRecordScreen;
    setState(() {
      print('setState');
      recording = !recording;
    });
    print("Opening video");
    print(path);
    OpenFile.open(path);
  }
}
`

**Comment by admarwick** [comment]
Please note that [PR #49](https://github.com/Isvisoft/flutter_screen_recording/pull/49) addresses this issue.

**Comment by salime45** [comment]
Fix
