### ISSUE TITLE
APP HAS STOPPED by calling FlutterScreenRecording.startRecordScreen

### ISSUE THREAD

**Issue by cs-mtahir** [Isvisoft/flutter_screen_recording#5]
**I want to record screen on flutter app** by using **flutter_screen_recording** plugin ,
but when i call **startRecordScreen(**) mehtod , app become crashed ,
error message showing like this:
FATAL EXCEPTION: main
E/AndroidRuntime( 8312): Process: com.example.my_screen_recording, PID: 8312
E/AndroidRuntime( 8312): java.lang.NoSuchMethodError: **No virtual method onActivityResult(ILandroid/content/Intent;Landroid/app/Activity;)**V in class Lcom/hbisoft/hbrecorder/HBRecorder; or its super classes (declaration of 'com.hbisoft.hbrecorder.HBRecorder' appears in /data/app/com.example.my_screen_recording-1/base.apk)
E/AndroidRuntime( 8312): 	at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:70)

**Comment by salime45** [comment]
You have, this lines in your app? 

allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }	    
    }
}
dependencies {
    implementation 'com.github.HBiSoft:HBRecorder:0.1.4'
}

**Comment by cs-mtahir** [comment]
Yes , i put these lines in my app ,
but it didn't work...

**Comment by salime45** [comment]
Have you try tyo execute the example app in the repo?

**Comment by cs-mtahir** [comment]
Yes , i did that , but same issue is arising...

**Comment by vvalladolidIV** [comment]
We have been updated the plugin. Could you try now?

**Comment by cs-mtahir** [comment]
yes ,
i tried  with new plugin , but it is creating empty video file .
