### ISSUE TITLE
Support more platforms

### ISSUE THREAD

**Issue by bdlukaa** [Isvisoft/flutter_screen_recording#52]
First of all, thank you for the awesome plugin :)

As flutter grows, we'd like this plugin to grow with it. It'd be great to have more supported platforms and a better api in the plugin. 

Currently supported platforms:

- [x] Android
- [x] iOS
- [ ] macOS
- [x] [web](https://github.com/Isvisoft/flutter_screen_recording/tree/web/flutter_screen_recording_web)

It'd also be great if we could take a screenshot using the plugin :)

**Comment by salime45** [comment]
hi, 

You can use the web branch https://github.com/Isvisoft/flutter_screen_recording/tree/web. For macOS there are not plans right now

**Comment by bdlukaa** [comment]
@salime45 It's good you support web, thanks :). You should mention that in the main page

**Comment by yogithesymbian** [comment]
hope macOS is support but less memory cause when recording game its make a game on lagging
