### ISSUE TITLE
execution failed for task ':flutter_screen_recording:compiledebugkotlin'.

### ISSUE THREAD

**Issue by SkilyFrance** [Isvisoft/flutter_screen_recording#55]
Hello Guys, 
Thanks for this plugin.

I updated Gradle to new version and now, this issue appears : 
**"execution failed for task ':flutter_screen_recording:compiledebugkotlin'".** 

**I tried many solutions but nothing works** : 
- Update 'classpath 'com.android.tools.build:gradle:3.5.0' to 4.1.1
- Update Kotlin from 1.3.50 to 1.3.72
- Run Flutter clean
- Run Flutter pub cache repair
- Delete pubspec.lock + Gradle (folder)
- Invalidate cache + wipe data from android device
- Test on device with Android 11.0, Android 10.0, Android 9.0

After 1 day on it, i decided to cut part of code. But i really want to use it. 
What can i do ? or What can you do (about updating package with new android updates) ?

Thanks for help.

Have a nice day,
Guillaume

**Comment by SkilyFrance** [comment]
Hey Guys, 
After searching others solutions : if you meet this log issue, try : 
- Remove your code working with flutter_screen_recording package
- Remove package from your pubspec.yaml
- Flutter clean + invalidate cache (android studio) + wipe data (emulator)
- Flutter build

I think this issue comes from .pubcache folder, so difficult to resolve without do the above process. 

Hope helpful,
Guillaume

**Comment by darshansatra1** [comment]
We don't have any other way?

**Comment by salime45** [comment]
Fix
