### ISSUE TITLE
Apps crash while click on Record Screen button and Record with Audio button doesn't work.

### ISSUE THREAD

**Issue by NayeemCseMu** [Isvisoft/flutter_screen_recording#56]
In my case build:gradle:4.1.0 doesn't work then I decrease the version to build:gradle:3.5.0 and it starts launching. But While I click on Record Screen Button it just crashed and Record with audio button also didn't work. Any solutions for these issues?

**Comment by matecija** [comment]
This is fixed in the latest version.
