### ISSUE TITLE
process image instead of saving it.

### ISSUE THREAD

**Issue by Hasankanso** [Isvisoft/flutter_screen_recording#60]
Hello, 
how do I get an instance of the recorded frame? I don't need to store the record, instead I want to do some processing on the image then throw it away.

is this possible?

**Comment by sunil3590** [comment]
@Hasankanso I have the same use case. Were you able to figure that out?

Also, does the plugin record the screen no matter which app is running? Or, does it only record the screen when the app is running on the foreground?
