### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by ameenvga** [Isvisoft/flutter_screen_recording#61]
When I run the example app (from pub. dev) I get the following error and the build is failing..

e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_screen_recording-1.1.1\android\src\main\kotlin\com\isvisoft\flutter_screen_recording\FlutterScreenRecordingPlugin.kt: (66, 87): Type mismatch: inferred type is Intent? but Intent was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_screen_recording-1.1.1\android\src\main\kotlin\com\isvisoft\flutter_screen_recording\FlutterScreenRecordingPlugin.kt: (171, 38): Type mismatch: inferred type is String? but String was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_screen_recording-1.1.1\android\src\main\kotlin\com\isvisoft\flutter_screen_recording\FlutterScreenRecordingPlugin.kt: (189, 38): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_screen_recording:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by mikron123** [comment]
Did you solve it?

**Comment by ameenvga** [comment]
Me? No!

**Comment by BayuWijayaPermanaPutra** [comment]
Any update about this issue?

**Comment by krishna949** [comment]
Same error i got, just committed in these lines its working fine for me
FlutterScreenRecordingPlugin.kt in these file u can commit 66 line and 171 and 189.

**Comment by salime45** [comment]
Fix
