### ISSUE TITLE
please support null safety

### ISSUE THREAD

**Issue by peter100u** [Isvisoft/flutter_screen_recording#66]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_screen_recording
 - package:flutter_foreground_plugin

**Comment by jeffreyliu8** [comment]
my workaround is pulling code and change it myself. https://github.com/Isvisoft/flutter_screen_recording/blob/master/lib/flutter_screen_recording.dart 
Just add like 4 required.

**Comment by peter100u** [comment]
i see, thank you&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeffrey ***@***.***&gt;; 
发送时间: 2021年8月25日(星期三) 上午7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Isvisoft/flutter_screen_recording] please support null safety (#66)






我的解决方法是自己提取代码并进行修改。https://github.com/Isvisoft/flutter_screen_recording/blob/master/lib/flutter_screen_recording.dart
只需要加 4 。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by WillianSalceda** [comment]
bump!

**Comment by WillianSalceda** [comment]
bump!

**Comment by kpusat** [comment]
Up

**Comment by ivantrave** [comment]
Up

**Comment by mminhlequang** [comment]
.
