### ISSUE TITLE
Record audio from both mic & internal speaker

### ISSUE THREAD

**Issue by thammaknot** [Isvisoft/flutter_screen_recording#72]
I'd like to use this plugin to record 

1. screen
2. audio from mic
3. audio from internal speaker

This plugin does not seem to handle (3). Does anyone have a solution for achieving this?

Thank you.

**Comment by ihorkozar** [comment]
@thammaknot, did you find any solution?

**Comment by thammaknot** [comment]
nope, unfortunately.
