### ISSUE TITLE
 supports the Android V2 embedding

### ISSUE THREAD

**Issue by jaish702** [Isvisoft/flutter_screen_recording#74]
Running "flutter pub get" in screenrecoder...                    1,378ms
The plugin `flutter_screen_recording` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by ivantrave** [comment]
Getting the same error

**Comment by deepak-ariceum** [comment]
Which error are you getting? Please be more specific.

**Comment by gmarimo** [comment]
> use this instead - https://github.com/endmr11/ed_screen_recorder

Have you managed to set enableAudio to true using this plugin? I have issues when I do so but it works well when it's set to false. do they support audio?

**Comment by tudosxxx** [comment]
pub get   ，  I have same error

**Comment by tudosxxx** [comment]
flutter_screen_recording 2.0.8,pub get ， I have same error

**Comment by jdevp** [comment]
Please migrate the plugin to the V2 embedding.

**Comment by tudosxxx** [comment]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_screen_recording' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61

too old

**Comment by jdevp** [comment]
Please update the package with V2 embedding and Kotlin Gradle plugin version 1.5.20 and higher

**Comment by x1h2** [comment]
> Android Gradle 插件仅支持 Kotlin Gradle 插件版本 1.5.20 及更高版本。 以下依赖项不满足所需版本： project ':flutter_screen_recording' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61
> 
> 太老

是呀，不支持了

**Comment by aruhant** [comment]
Would the maintainers be willing to accept a PR for this ?

**Comment by salime45** [comment]
all contributions are welcome

**Comment by TNorbury** [comment]
PR is open. See the PR description for instructions on how to use my branch in your project
