### ISSUE TITLE
The plugin `flutter_screen_recording` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Khawajafakhar** [Isvisoft/flutter_screen_recording#79]
The plugin `flutter_screen_recording` uses a deprecated version of
the Android embedding.
To avoid unexpected runtime failures, or future build failures, try
to see if this plugin supports the Android V2 embedding. Otherwise,
consider removing it since a future release of Flutter will remove
these deprecated APIs.

**Comment by salime45** [comment]
Duplicate
