### ISSUE TITLE
Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

### ISSUE THREAD

**Issue by M4H3NDR4N** [Isvisoft/flutter_screen_recording#8]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=333, result=-1, data=Intent { (has extras) }} to activity {com.isvisoft.flutter_screen_recording_example/com.isvisoft.flutter_screen_recording_example.MainActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime(29458):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(29458):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(29458):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(29458):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29458):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29458):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(29458):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29458):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(29458):        at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(29458):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29458):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29458):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(29458): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime(29458):        at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(29458):        at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(29458):        at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(29458):        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime(29458):        at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
E/AndroidRuntime(29458):        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
E/AndroidRuntime(29458):        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:71)
E/AndroidRuntime(29458):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(29458):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:131)        
E/AndroidRuntime(29458):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(29458):        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime(29458):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(29458):        ... 11 more
E/AndroidRuntime(29458): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(29458):        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
E/AndroidRuntime(29458):        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime(29458):        at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime(29458):        at android.os.Binder.execTransact(Binder.java:994)
E/AndroidRuntime(29458):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(29458): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime(29458):        at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(29458):        at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(29458):        at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(29458):        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime(29458):        at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
E/AndroidRuntime(29458):        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
E/AndroidRuntime(29458):        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:71)
E/AndroidRuntime(29458):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(29458):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:131)        
E/AndroidRuntime(29458):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(29458):        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime(29458):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(29458):        ... 11 more

**Comment by M4H3NDR4N** [comment]
After adding <application android:foregroundServiceType="mediaProjection"> </application> to AndroidManifest.xml, It worked.

**Comment by abdullah432** [comment]
@M4H3NDR4N This line does not work for me. Did you use compileSdkVersion 28 or 29. I'm using 29 and it's not working for me
