### ISSUE TITLE
Error onMethodCall startRecordScreen

### ISSUE THREAD

**Issue by sherdiltahir** [Isvisoft/flutter_screen_recording#89]
D/MediaRecorder(20517): constructor+ 0xb400007e277d2100
D/MediaRecorder(20517): constructor- 0xb400007e277d2100
I/System.out(20517): Error onMethodCall startRecordScreen
I/System.out(20517): null

**Comment by abundiko** [comment]
I faced the same issue and fixed it by adding

```
titleNotification: "recording active",
messageNotification: "..."
```

but now Whenever I click the start now button, my app crashes

**Comment by TNorbury** [comment]
@abundiko I was experiencing the same issue, but was able to resolve it by adding
```
<service
    android:name="com.foregroundservice.ForegroundService"
    android:foregroundServiceType="mediaProjection">
</service>
```

to my Android Manifest
