### ISSUE TITLE
How to get permission?

### ISSUE THREAD

**Issue by abdullah432** [Isvisoft/flutter_screen_recording#9]
When i install example of flutter_screen_recording. It automatically popup for permission. But when i request permission after adding dependency app does not popup for permission. 
I check code for getting permission in example but didn't found any. I'm wondering how the example get permission.
I know "Flutter_Screen_Recorder do not request permissions necessary.".

**Comment by salime45** [comment]
in the readme apear the info.

Flutter_Screen_Recorder do not request permissions necessary. You can use Permission_handler, a permissions plugin for Flutter.

**Comment by salime45** [comment]
https://pub.dev/packages/permission_handler

**Comment by abdullah432** [comment]
Thanks for replay. I read that but wondering how your github example request permission. I check permission plugin in your github example but didn't found you use it. I'm currently implementing it. That's just general question if you want to answer.

**Comment by abdullah432** [comment]
Also which permission is needed for screen recording.

**Comment by abdullah432** [comment]
Sir i'm waiting for your answer. I didn't now which permission is needed for screen recording. I already give following permission.
1) android.permission.RECORD_AUDIO
2) android.permission.WRITE_EXTERNAL_STORAGE
3) android.permission.READ_EXTERNAL_STORAGE
But still not able to screen record. Which permission is needed for screen recording.
