### ISSUE TITLE
On Android, it starts recording even before the 'start now' button is pressed on the native popup

### ISSUE THREAD

**Issue by akshayOnform** [Isvisoft/flutter_screen_recording#94]
![ttttttt](https://github.com/Isvisoft/flutter_screen_recording/assets/140606631/92c8c4a6-9be9-4415-8f1c-75bce6bffc76)

I fixed this for now by making this change.
https://github.com/akshayOnform/flutter_screen_recording/pull/6

**Comment by kyadalu1** [comment]
Try this https://www.youtube.com/watch?v=eMLhAtcfkAs
